AllCops:
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  Exclude:
    - lib/calculated_attributes/rails_*_patches.rb
    - vendor/**/*

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: False
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": ()
Style/StringLiterals:
  Exclude:
    - gemfiles/*.gemfile
