version: 2
jobs:
  test:
    working_directory: ~/calculated_attributes
    docker:
      - image: cimg/ruby:3.1.3
        environment:
          GEM_HOME: ~/calculated_attributes/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v2-{{ checksum "calculated_attributes.gemspec" }}
      - run:
          name: Install bundle dependencies
          command: |
            bundle check --path=vendor/bundle || bundle install --jobs=4 --retry=3 --path=vendor/bundle
      - run:
          name: Appraisal-install
          command: bundle exec appraisal install
      - save_cache:
          key: dependency-cache-v2-{{ checksum "calculated_attributes.gemspec" }}
          paths:
            - vendor/bundle
      - run:
          name: RSpec
          command: bundle exec appraisal rspec
      - run:
          name: rubocop
          command: bundle exec rubocop

workflows:
  version: 2
  test:
    jobs:
      - test
