u = User.create(username: 'test')
User.create(username: 'unused')
p = Post.create(text: 'First post!', user: u)
Comment.create(post_id: p.id, text: 'First comment!', user: u)
Post.create(text: 'Second post!')
t = Tutorial.create(text: 'Tutorial!')
Comment.create(post_id: t.id, text: 'First comment!')
a = Article.create(text: 'Article!')
Comment.create(post_id: a.id, text: 'First comment!')
