p = Post.create(text: "First post!")
Comment.create(post_id: p.id, text: "First comment!")
Post.create(text: "Second post!")
t = Tutorial.create(text: "Tutorial!")
Comment.create(post_id: t.id, text: "First comment!")
a = Article.create(text: "Article!")
Comment.create(post_id: a.id, text: "First comment!")